set shell=/bin/bash
set so=7
set ai
set expandtab
set tabstop=2
set shiftwidth=2
set autoindent
set smartindent
set title
set incsearch
set hlsearch
set ignorecase
set smartcase
set wildmode=longest,list,full
set wildmenu
set showcmd
set report=0
set number
set lazyredraw
set ttyfast
set directory=/var/tmp
set backspace=indent,eol,start
set updatetime=300
set cmdheight=1
set nowrap
syntax on
syntax enable
map <C-s> :execute "so %"<CR>
silent !stty -ixon > /dev/null 2>/dev/null
nnoremap <CR> :nohlsearch<CR>
let mapleader = ","

" Auto remove trailing whitespaces
autocmd FileType c,cpp,java,php,scala,python,ruby autocmd BufWritePre <buffer> %s/\s\+$//e 

call plug#begin('~/.local/share/nvim/plugged')
  Plug 'scrooloose/nerdTree'
  Plug 'itchyny/lightline.vim'
  Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}

  " Tools
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
  Plug 'junegunn/fzf.vim'
  Plug 'terryma/vim-multiple-cursors'

  " Themes
  Plug 'rafi/awesome-vim-colorschemes'

  " Languages
  Plug 'rust-lang/rust.vim'
  Plug 'derekwyatt/vim-scala'
call plug#end()

" Dark Rustic Themes
"colorscheme deus
"colorscheme happy_hacking

" Medium Pristine Themes
"colorscheme seoul256
"colorscheme nord
let g:challenger_deep_termcolors = 16
colorscheme challenger_deep

""" FZF
map <C-p> :execute "GFiles"<CR>
map <C-l> :execute "Lines"<CR>
map <C-m> :execute "Marks"<CR>

""" NERDTREE
map <C-e> :NERDTreeToggle<CR>
let NERDTreeMapOpenVSplit = '<C-v>'
let NERDTreeMapOpenInTab = '<C-t>'
let NERDTreeMapOpenSplit = '<C-s>'

""" FILE SPECIFIC
au FileType fish compiler fish
au BufNewFile,BufRead *.ms set filetype=javascript
au BufNewFile,BufRead *.pegjs set filetype=javascript
au BufNewFile,BufRead *.jsx set filetype=javascript
au BufNewFile,BufRead *.cjsx set filetype=javascript
au BufNewFile,BufRead *.cap set filetype=ruby
au BufNewFile,BufRead *.ejs set filetype=html
au BufNewFile,BufRead Gemfile set filetype=ruby
au! BufRead,BufNewFile *.json set filetype=json
au! FileType c,cpp,java,php call CSyntaxAfter()
au BufRead,BufNewFile *.sbt set filetype=scala
autocmd FileType json syntax match Comment +\/\/.\+$+

""" COC Plugin
nnoremap <silent> <space>a  :<C-u>CocList diagnostics<cr>
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

let g:lightline = {
      \ 'colorscheme': 'challenger_deep',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'cocstatus', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'cocstatus': 'coc#status'
      \ },
      \ }

