set shell=/bin/sh
set ai
set expandtab
set tabstop=2
set shiftwidth=2
set background=dark
set nowrap
set autoindent
set smartindent
set title
set restorescreen 
set hlsearch
set incsearch
set ignorecase
set smartcase
set wildmode=longest,list,full
set wildmenu
set laststatus=2
set showcmd
set report=0

syntax on
syntax enable
filetype on
filetype plugin indent on
map <C-s> :execute "vimgrep /" . expand("<cword>") . "/j **" <Bar> cw<CR>
silent !stty -ixon > /dev/null 2>/dev/null
au BufNewFile,BufRead *.ms set filetype=javascript
au BufNewFile,BufRead *.cap set filetype=ruby
au BufNewFile,BufRead *.ejs set filetype=html
autocmd BufNewFile,BufRead Gemfile set filetype=ruby
nnoremap <CR> :noh<CR>
hi Sejrch cterm=NONE ctermfg=black ctermbg=white

" Useful key mappings
imap ;co console.log();<left><left>
imap ;ri raise .inspect<left><left><left><left><left><left><left><left>

" Everything after this line requires plugins

call pathogen#infect()

"Clojure
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" CTRL-p
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
let g:ctrlp_use_caching = 0

" EASYMOTION
let g:EasyMotion_leader_key = '<Leader>'
hi EasyMotionTarget ctermbg=none ctermfg=blue
hi EasyMotionShade  ctermbg=none ctermfg=black

" NERDTree
map <C-n> :NERDTreeToggle<CR>

python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup

" Tmux Navigator
let g:tmux_navigator_no_mappings = 1

nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
nnoremap <silent> <c-l> :TmuxNavigateRight<cr>
