#!/bin/bash

export OSTACK_IP=10.20.10.121
export PROJECTS_DIR=~/code/projects
export WORKSPACE_DIR=~/code/workspace
export CONFIGS_DIR=$PROJECTS_DIR/configs
export BIN_DIR=~/code/bin

alias s='source ~/.bashrc'

# Jump to Frequented Directories
alias f='cd $PROJECTS_DIR'
alias w='cd $WORKSPACE_DIR'
alias b='cd $BIN_DIR'

# Various
alias r='echo "SSHing to openstack machine" && ssh kevin@$OSTACK_IP'
alias saveconfs='echo "Saving configuration files" && (cd $CONFIGS_DIR && git add . && git commit -m "Latest updates" && git push)'
alias ha='ssh root@haproxy1 cat /etc/haproxy/haproxy.cfg'
alias vine-m='mongo 10.20.10.147'
alias docdev='eval $(docker-machine env dev)'
alias docneu='eval $(docker-machine env neutronic)'
alias mcc='mvn clean compile'
alias mej='mvn exec:java'
alias js="jq '.'"
