#!/bin/bash

export OSTACK_IP=10.20.10.121
export OFFICE_IP=10.0.100.99
export PROJECTS_DIR=~/code/projects
export WORKSPACE_DIR=~/code/workspace
export CONFIGS_DIR=$PROJECTS_DIR/configs
export BIN_DIR=~/code/bin
export JAVA_HOME=$(/usr/libexec/java_home)
export THIS_FILE=$CONFIGS_DIR/bash/odyssey_profile 

# Display Shortcuts
alias sh='cat $THIS_FILE | grep alias'

# Display Environment Variables
alias ev='cat $THIS_FILE | grep "export\s"'

# Jump to Frequented Directories
alias f='cd $PROJECTS_DIR'
alias w='cd $WORKSPACE_DIR'
alias b='cd $BIN_DIR'

# Various
alias r='echo "SSHing to openstack machine" && ssh kevin@$OSTACK_IP'
alias o='echo ""SSHing to office machine" && ssh kevin@$OFFICE_IP'
alias saveconfs='echo "Saving configuration files" && (cd $CONFIGS_DIR && git add . && git commit -m "Latest updates" && git push)'
alias ha='ssh root@haproxy1 cat /etc/haproxy/haproxy.cfg'
alias vine-m='mongo 10.20.10.147'
alias dm='docker-machine'
alias dme='eval $(docker-machine env dev)'

# Launch process commands that I never remember
alias postgres='postgres -D /usr/local/var/postgres'
alias es='elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml'

#if [[ `docker-machine status default` =~ "Running" ]]; then
#  echo "Sourcing Docker-machine environment variables"
#  eval $(docker-machine env dev)
#fi

export PATH=/usr/local/sbin:$PATH
