#!/bin/bash

export OSTACK_IP=10.20.10.121
export OFFICE_IP=10.0.100.99
export PROJECTS_DIR=~/code/projects
export WORKSPACE_DIR=~/code/workspace

alias f='cd $PROJECT_DIR'
alias w='cd $WORKSPACE_DIR'
alias r='echo "SSHing to openstack machine" && ssh kevin@$OSTACK_IP'
alias o='echo ""SSHing to office machine" && ssh kevin@$OFFICE_IP'
alias save_configs='echo "Saving configuration files" && $(cd $PROJECTS_DIR/configs && git add . && git commit -m "Latest updates" && git push)'
alias postgres='postgres -D /usr/local/var/postgres'
alias es='elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml'
export JAVA_HOME=$(/usr/libexec/java_home)

if ls $(pwd) | grep 'Dockerfile' 2>&1 >> /dev/null && [[ `docker-machine status default` =~ "Running" ]]; then
  echo "Sourcing Docker-machine environment variables"
  eval $(docker-machine env default)
fi
