#!/bin/bash
export EDITOR=vim

export OFFICE_IP=10.0.201.127
export WORKSPACE_DIR=~/Workspace
export PROJECTS_DIR=$WORKSPACE_DIR/code/projects
export CONFIGS_DIR=$PROJECTS_DIR/configs

export HISTCONTROL="erasedups:ignoreboth"
export HISTFILESIZE=500000
export HISTSIZE=100000
export HISTIGNORE="&:[ ]*:exit"
shopt -s histappend
shopt -s cmdhist

alias tl='tmux list-sessions'
alias ta='tmux attach -t'
alias gd='git diff HEAD *'
alias gs='git status'
alias gc='git commit -m'
alias ga='git add .'
alias s='source ~/.bash_profile'
alias f='cd $PROJECTS_DIR'
alias saveconfs='echo "Saving configuration files" && (cd $CONFIGS_DIR && git add . && git commit -m "Latest updates" && git push)'

alias ls='ls -G'

START="\e["
STOP="\e[m"
BLUE="\[0;34m\]"
L_GREEN="\[0;92m\]"
CYAN="\[0;36m\]"
YELLOW="\[0;33m\]"
MAGENTA="\[0;35m\]"

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="${START}${L_GREEN}\w${STOP}${START}${MAGENTA}\$(parse_git_branch)${STOP} ${START}${YELLOW}>${STOP} "


# PATHS
export PATH=/usr/local/sbin:$PATH

## Use brew version of Bison
export PATH="/usr/local/opt/bison/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

export PATH="$HOME/.cargo/bin:$PATH"
