#!/bin/bash
#
# dzen2 taskbar by heepster
#

TOTAL_DESKTOPS=3 # how to get this programmatically?
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/bar_config

function printDesktop () {
  #echo "^pa(-300)${DESKTOP_ICON} $(($(xprop -root _NET_CURRENT_DESKTOP | cut -d '=' -f '2') + 1)) / ^fg($BLUE)$TOTAL_DESKTOPS^fg()^p()"
  echo "^pa(0,0)^p(-1000)${DESKTOP_ICON} $(($(xprop -root _NET_CURRENT_DESKTOP | cut -d '=' -f '2') + 1)) / ^fg($BLUE)$TOTAL_DESKTOPS^fg()^p()"
}

function printMusic() {
  info=$(cmus-remote -Q)

  if [[ $? -eq 0 ]]; then
    status=$(echo -e "$info" | grep status | cut -d ' ' -f 2)
    artist=$(echo -e "$info" | grep artist | cut -d ' ' -f 3- | head -n 1)
    song=$(echo -e "$info" | grep title | cut -d ' ' -f 3- | head -n 1)
    echo "${MUSIC_ICON}  ${artist} - ${song}"
  else
    echo ""
  fi
}

function printDate() {
  echo -e "^fg($BROWN)$(date '+%a %b %d %I:%M:%S')^fg()"
}

function printVolume() {
  vol=$(amixer -c 1 get Master | grep % | sed -n 1p | awk -F '[' '{print $2}' | awk -F ']' '{print $1}')

  if [ $vol = '0%' ]; then
    echo -e "^fg($RED)${VOL_OFF_ICON}^fg()$vol"
  else
    echo -e "^fg($BLUE)${VOL_ICON}^fg()$vol" 
  fi
}

function printBrightness() {
  brightness=$(xbacklight | cut -d '.' -f 1)
  echo -e "^fg($YELLOW)${LIGHT_ICON}^fg()$brightness%"
}

function printBattery() {
  batInfo=$(acpi)
  batPercentage=$(echo $batInfo | cut -d ',' -f 2 | cut -d '%' -f 1)

  if [[ $batInfo =~ .*Discharging.* || $batInfo =~ .*Full.* ]]; then
    if [[ "$batPercentage" -gt "90" ]]; then
      BAT_ICON=$BAT_4_ICON
    elif [[ "$batPercentage" -gt "70" ]]; then
      BAT_ICON=$BAT_3_ICON
    elif [[ "$batPercentage" -gt "40" ]]; then
      BAT_ICON=$BAT_2_ICON
    elif [[ "$batPercentage" -gt "10" ]]; then
      BAT_ICON=$BAT_1_ICON
    else
      BAT_ICON=$BAT_0_ICON
    fi
  elif [[ $batInfo =~ .*Charging.* ]]; then
    BAT_ICON="$BOLT_ICON"
  fi

  echo -e "${BAT_ICON}${batPercentage}%"
}

while :; do
  echo -e "$(printDesktop)      $(printMusic)       $(printVolume)  $(printBrightness)  $(printBattery)       $(printDate)  "
	sleep 0.1
done | dzen2 -p -fg "$FG" -bg "$BG" -fn "$FONT" -ta "r" -xs 1
